# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import unmango_pulumi_talos.client as __client
    client = __client
    import unmango_pulumi_talos.cluster as __cluster
    cluster = __cluster
    import unmango_pulumi_talos.machine as __machine
    machine = __machine
else:
    client = _utilities.lazy_import('unmango_pulumi_talos.client')
    cluster = _utilities.lazy_import('unmango_pulumi_talos.cluster')
    machine = _utilities.lazy_import('unmango_pulumi_talos.machine')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "talos",
  "mod": "machine/bootstrap",
  "fqn": "unmango_pulumi_talos.machine",
  "classes": {
   "talos:machine/bootstrap:Bootstrap": "Bootstrap"
  }
 },
 {
  "pkg": "talos",
  "mod": "machine/configurationApply",
  "fqn": "unmango_pulumi_talos.machine",
  "classes": {
   "talos:machine/configurationApply:ConfigurationApply": "ConfigurationApply"
  }
 },
 {
  "pkg": "talos",
  "mod": "machine/secrets",
  "fqn": "unmango_pulumi_talos.machine",
  "classes": {
   "talos:machine/secrets:Secrets": "Secrets"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "talos",
  "token": "pulumi:providers:talos",
  "fqn": "unmango_pulumi_talos",
  "class": "Provider"
 }
]
"""
)
